# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: tempconv.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'tempconv.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0etempconv.proto\x12\x08tempconv\"#\n\x12TemperatureRequest\x12\r\n\x05value\x18\x01 \x01(\x01\"$\n\x13TemperatureResponse\x12\r\n\x05value\x18\x01 \x01(\x01\x32\xb2\x01\n\x08TempConv\x12R\n\x13\x43\x65lsiusToFahrenheit\x12\x1c.tempconv.TemperatureRequest\x1a\x1d.tempconv.TemperatureResponse\x12R\n\x13\x46\x61hrenheitToCelsius\x12\x1c.tempconv.TemperatureRequest\x1a\x1d.tempconv.TemperatureResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'tempconv_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TEMPERATUREREQUEST']._serialized_start=28
  _globals['_TEMPERATUREREQUEST']._serialized_end=63
  _globals['_TEMPERATURERESPONSE']._serialized_start=65
  _globals['_TEMPERATURERESPONSE']._serialized_end=101
  _globals['_TEMPCONV']._serialized_start=104
  _globals['_TEMPCONV']._serialized_end=282
# @@protoc_insertion_point(module_scope)
